# Kubernetes Secrets Template
# 
# This file contains template for creating the required secrets.
# DO NOT commit this file with real values!
#
# To create the secrets, run:
#
# kubectl create secret generic app-secrets \
#   --from-literal=mongodb-uri='mongodb://mongodb-service:27017/parapharmacy' \
#   --from-literal=jwt-secret='your-super-secret-jwt-key-here'
#
# Or apply this file after replacing the values:
# kubectl apply -f secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # MongoDB connection string
  mongodb-uri: "mongodb://mongodb-service:27017/parapharmacy"
  
  # JWT secret for authentication
  jwt-secret: "your-super-secret-jwt-key-here-change-this-in-production" 